In [24]:
import numpy as np

In [46]:
m = np.random.randint(10, size=10)
n = np.random.randint(10, size=10)
k = np.random.randint(10, size=10)
print(m, n, k)

[5 6 4 8 6 8 6 4 4 2] [0 5 5 8 4 4 7 0 3 3] [1 2 4 4 9 3 2 9 7 0]


In [56]:

print(np.mean(m), np.median(m))
print(np.std(m), np.std(m)**2)

print(np.mean(n), np.median(n))
print(np.std(n), np.std(n)**2)

a = np.concatenate((m,n,k), axis=0)
a = a.reshape((3,10))
print(a)

np.cov(a)

5.3 5.5
1.7916472867168918 3.2100000000000004
3.9 4.0
2.4677925358506134 6.090000000000001
[[5 6 4 8 6 8 6 4 4 2]
 [0 5 5 8 4 4 7 0 3 3]
 [1 2 4 4 9 3 2 9 7 0]]


array([[ 3.56666667,  2.58888889,  0.18888889],
       [ 2.58888889,  6.76666667, -1.65555556],
       [ 0.18888889, -1.65555556, 10.32222222]])

In [59]:
from numpy import linalg as LA

In [62]:
m = np.array([[3,0,1],[-4,1,2],[-6,0,-2]])
w, v = LA.eig(m)
print(w)
print(v)

[ 1.00000000e+00  1.00000000e+00 -2.22044605e-16]
[[ 0.00000000e+00  5.55111512e-17 -9.53462589e-02]
 [ 1.00000000e+00 -1.00000000e+00 -9.53462589e-01]
 [ 0.00000000e+00 -1.11022302e-16  2.86038777e-01]]
